# Generated by Django 4.1.4 on 2022-12-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False, verbose_name='MovieId')),
                ('title', models.CharField(max_length=511, verbose_name='title')),
                ('adult', models.BooleanField(default=False, verbose_name='adult')),
                ('imdbid', models.IntegerField(verbose_name='imdbid')),
                ('backdrop', models.CharField(blank=True, max_length=255, null=True, verbose_name='backdrop')),
            ],
        ),
    ]
