# Generated by Django 4.1.4 on 2022-12-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdbid',
            field=models.CharField(max_length=511, verbose_name='imdbid'),
        ),
    ]
