# Generated by Django 4.1.4 on 2022-12-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forming', '0002_alter_movies_imdbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='imdbid',
        ),
    ]
