# Generated by Django 4.1.4 on 2022-12-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forming', '0003_remove_movies_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imdbid',
            field=models.CharField(default='aaa', max_length=511, verbose_name='imdbid'),
            preserve_default=False,
        ),
    ]
