# Generated by Django 4.1.4 on 2022-12-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forming', '0004_movies_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='genres'),
        ),
    ]
