# Generated by Django 4.1.4 on 2022-12-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forming', '0005_movies_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='overviews',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='overviews'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='genres'),
        ),
    ]
